### ISSUE TITLE
[timeline] click target for chart labels

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1034]
chart labels can link to the browser page for sv + place

e.g. in the screenshot below, California --> https://datacommons.org/browser/geoId/06?statVar=Annual_Consumption_Coal_ElectricPower

![image](https://user-images.githubusercontent.com/6052978/125527424-751d8095-6157-43b8-8368-01ed78d64a05.png)

**Comment by chejennifer** [comment]
when it's a single place, those labels show the stat vars. In those cases, do we still want the labels to link to browser page for sv + place? I feel like it might be a little confusing if both the chips and those labels have the same text but link to different places?

**Comment by beets** [comment]
good point - for a single place, the legend should also be the place label for consistency. wdyt?

**Comment by chejennifer** [comment]
I think that could be confusing for single place + multiple stat vars because the legend would just have that same place repeated multiple times? Maybe the legend could be "{statvar} - {place}"

**Comment by beets** [comment]
i like that - maybe {statVar} ({place})

single place, n statvar --> link to stat var x place page, and label is {statVar} ({place})
multi place, multi statvar --> link to place page, label stays as {place}

**Comment by chejennifer** [comment]
thinking about it, I think it makes more sense to do:

single statvar -> link to stat var x place page & label is {stat var} ({place})
multi statvar -> link to place page, label stays as {place}

**Comment by shifucun** [comment]
I feel click target to the graph browser is more helpful than the place page. If I want to know more about those stat vars of a place, the place page does not tell much (and have no way to find where they are..)

I wonder if we should have a simple page that shows a list of "place stat var" page links and the click target goes there. This would be much more helpful for debugging etc.

Another option is to allow the graph browser expand for multiple stat vars, which is doable given the recent changes. That will also help for debugging and seeing all the different charts for a given stat var (which is the most popular use of it).

When there is a single place, showing {stat var} {place} is a bit surprising as the place just feel redundant there. I still vote for just showing the stat var label. 

If there is concern on chip and label leading to different places. Maybe we should have a way to click from the stat var hierarchy to the stat var explorer when it is available. Since there is no chip in other tools anyway, and the function to explore the stat var information should belong to the hierarchy rather than the chart region?

**Comment by chejennifer** [comment]
I agree that graph browser will be more helpful than the place page. 

I think the browser can already be expanded for multiple stat vars. Do you mean allowing the graph browser page to render with those stat vars already expanded when the user goes to a specific url?

I think chip and label having the same text but leading to different places would be confusing for the user. But we could think about how to click from the stat var hierarchy instead of the chip. Or maybe have a separate click target for going to the stat var explorer.

**Comment by beets** [comment]
Consider the case of a single place, but many stat vars ([example](https://autopush.datacommons.org/tools/timeline#place=geoId%2F06&statsVar=GenderIncomeInequality_Person_15OrMoreYears_WithIncome__LifeExpectancy_Person__Count_Person_PerArea__Median_Income_Person__Count_Person__dc%2Fc17kzp0zrfkq9)). As you scroll, the context of the place is easily lost, and each chart is no longer standalone. The stat var legend labels also become redundant with the chips.

I think linking to the graph browser page with the stat vars expanded sounds good. That sounds sufficient though, and hoping we don't need to make it more complicated if we can avoid it.

**Comment by shifucun** [comment]
Okay, using graph browser for all click targets sounds good. I am okay with the label name change, we can see how it looks like for more cases.

**Comment by chejennifer** [comment]
ok, so:

single statvar -> link to stat var x place page & label is {stat var} ({place})
multi statvar -> link to place page with all stat vars expanded, label stays as {place}

**Comment by beets** [comment]
yea that sounds good!
