### ISSUE TITLE
[tree widget] tooltips should apply to top-level sv groups too

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1038]
there are some states, such as [this](https://autopush.datacommons.org/tools/timeline#&&place=geoId/1304000,geoId/4982950&statsVar=Median_Income_Person), where the top-level groups are grayed out. the same tooltips describing unavailability / explaining count should also apply there

**Comment by chejennifer** [comment]
Currently we don't have the placetype/example places information for stat var groups .. so there is an "i" icon at the top of the stat var hierarchy to explain what counts and greyed out means. I feel like showing the information this way will create less noise on the page?

**Comment by beets** [comment]
ah got it. the (i) might be too far away from the sv's, maybe we can move it to below the search box

**Comment by chejennifer** [comment]
but in a fixed position? I think the only problem with this is that we'll need a bigger gap between where the input box is and where the hierarchy sections start which might look odd .. because otherwise, if we scroll down and there's a stat var that fills the whole width of the widget, it will cause overlapping problems
