### ISSUE TITLE
Timeline tool: per chart option toggle

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/website#229]
Each chart corresponding to one or multiple stats vars with same measured value. But there could be other stats observation properties to choose: **observationPeriod**, **unit**, **scaling factor**, **measurementMethod**. We should give user the option to toggle among these.

It's also nice to have perCapita, logScale as a toggle on per chart basis.

@beets what would be a good UI for this? A naive solution is to have a dropdown menu by the chart.

**Comment by beets** [comment]
This seems like an advanced feature, for someone in tune with the data that we have :) 

Will we be able to know what all the possible options are? Will the options apply to all lines in a chart (since we currently group by mmethod I believe?) Then we could add a dropdown in the top or bottom left corner with the options to choose from.
