### ISSUE TITLE
[NL] query for palo alto doesn't work

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#2348]
![image](https://user-images.githubusercontent.com/4375037/222020822-817aa952-c193-4f87-a51f-b59f6ddd7c3e.png)

**Comment by pradh** [comment]
I suspect it is because places API is returning ChIJS_un3b1NIYYRvTdUFxla-0o instead of ChIJORy6nXuwj4ARz3b1NVL1Hw4.

The former is a TYPE_COLLOQUIAL_AREA, while latter is TYPE_LOCALITY, and preferable.  Though I don't know why the API started returning that.  Our auto-complete is still fine.

**Comment by jehangiramjad** [comment]
After doing some frustrating debugging, the analysis suggested here seems correct: this is the Maps API returning a different type of location. What is frustrating is that whenever accessing autopush (or the dev instance) from europe (autopush and dev both appear to have deployments in europe), the Maps API returns the "correct" Palo Alto. So this is a location issue because Maps API is sensitive to the query location. I will investigate further to see what we can do to prevent this behavior.
