### ISSUE TITLE
City rendering in Choropleth

### ISSUE THREAD

**Issue by fpernice-google** [datacommonsorg/website#383]
## Problem
Currently, the sub-county view in Choropleth is of cities. However, cities do not partition counties. Two issues arise from this:

1. Some counties aren't fully covered by cities. For example, San Mateo County has a large "empty" space between Half Moon Bay and Highlands-Baywood Park/Hillsborough. This corresponds to a mountainous area according to @jeffreyoldham. This results in sections of the county being displayed in white, which seems visually off.
2. Some cities aren't fully within a single county. Examples of this are New York City and Houston. This is currently very badly handled by Choropleth, in some cases not displaying these counties at all (like in the case of NYC), and in other cases displaying the same city plot under multiple counties (like in the case of Houston).

## Suggested Solution
To explicitly draw out the county boundaries. This way, problem (1) would be addressed by explicitly showing the user what the "empty" areas are. Moreover, problem (2) would be addressed, because even if cities are drawn that exceed county boundaries, the section of the city that lies within the county would be clearly marked. 

> NOTE: Cases like the one in NYC where counties are ignored would have to be addressed separately.

**Comment by fpernice-google** [comment]
@beets @jeffreyoldham @edumorlom tagged for visibility.

**Comment by jeffreyoldham** [comment]
One more case is where a city is its county-equivalent.  San Francisco, Baltimore, and Denver have combined their city and county governments.  Independent cities such as Carson City, NV, and many in Virginia may also be impacted.  The District of Columbia (more precisely Washington, DC) may also be impacted.

Asking for city-level data for these cities may not yield data because it is available at the county level.  Thus, the city-level data pulls may not yield values except when specially handled.

**Comment by pradh** [comment]
Nice examples Jeffrey.

Turns out that Census includes geo-coordinate info for each of those entities, and they match.

SF city vs. county:
- https://api.datacommons.org/node/property-values?dcids=geoId/0667000&property=geoJsonCoordinates&direction=out
- https://api.datacommons.org/node/property-values?dcids=geoId/06075&property=geoJsonCoordinates&direction=out

DC city vs. county vs. state equivalents:
- https://api.datacommons.org/node/property-values?dcids=geoId/1150000&property=geoJsonCoordinates&direction=out
- https://api.datacommons.org/node/property-values?dcids=geoId/11001&property=geoJsonCoordinates&direction=out
- https://api.datacommons.org/node/property-values?dcids=geoId/11&property=geoJsonCoordinates&direction=out

**Comment by shifucun** [comment]
Now the lowest level of place type is County not City anymore. This issue seems obsolete. @chejennifer can you confirm to close this?

**Comment by chejennifer** [comment]
Correct that lowest level of place type is County instead of City, but we might add cities in the future. Closing this issue for now and if we add cities in the future, will keep this stuff in mind.
