### ISSUE TITLE
PV Tree issues

### ISSUE THREAD

**Issue by rvguha** [datacommonsorg/website#385]
See 

https://datacommons.org/tools/timeline#place=geoId%2F06025&statsVar=Amount_EconomicActivity_GrossDomesticProduction_RealValue%2C9%2C4%2C0%2C3__WagesAnnual_Establishment%2C9%2C0&chart=%257B%2522count%2522%253A%257B%2522pc%2522%253Afalse%257D%257D

Two issues:

1. What does 8G mean? What is "G"

2. The text is quite confusing: what does "Annual Wages of Establishment" mean? Similarly, what does "Activity Source" mean?

**Comment by beets** [comment]
Updated link: https://datacommons.org/tools/timeline#place=geoId%2F06025&statsVar=WagesAnnual_Establishment__Amount_EconomicActivity_GrossDomesticProduction_RealValue

![image](https://user-images.githubusercontent.com/6052978/140802886-a8171e6e-f45a-4aa1-a1fb-c3c57a406243.png)

(not sure if 8G is still a problem - axis labels are 8B so that might have been fixed.)
