### ISSUE TITLE
How to generate QUOTA_PROJECT_ID for Minikube

### ISSUE THREAD

**Issue by LorenHeyns** [datacommonsorg/website#812]
### Feedback
When installing Minikube, a QUOTA_PROJECT_ID is needed.
Where do we generate this ID?

### About
URL: https://github.com/datacommonsorg/website/blob/master/developer_guide.md

To reproduce the behavior run: brew install minikube

Is there a beta QUOTA_PROJECT_ID or do we create a project in our Google account? If so, what's the start page?

**Comment by shifucun** [comment]
Minikube is a local Kubernetes environment and should not be related to Google account. Can you paste the full error msg here? Also for local development, it's easier to use the [Simple/Lite flow](https://github.com/datacommonsorg/website/blob/master/developer_guide.md#develop-with-flask-simplelite) instead of using the Docker approach.

**Comment by datascape** [comment]
I ran `minikube start` based on the minikube link on the [Developer Guide](https://github.com/datacommonsorg/website/blob/master/developer_guide.md).

minikube start
😄  minikube v1.17.1 on Darwin 10.15.6
✨  Automatically selected the hyperkit driver
💾  Downloading driver docker-machine-driver-hyperkit:
    > docker-machine-driver-hyper...: 65 B / 65 B [----------] 100.00% ? p/s 0s
    > docker-machine-driver-hyper...: 11.44 MiB / 11.44 MiB  100.00% 19.62 MiB 
🔑  The 'hyperkit' driver requires elevated permissions. The following commands will be executed:

    $ sudo chown root:wheel /Users/helix/.minikube/bin/docker-machine-driver-hyperkit 
    $ sudo chmod u+s /Users/helix/.minikube/bin/docker-machine-driver-hyperkit 


Password:
💿  Downloading VM boot image ...
    > minikube-v1.17.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.17.0.iso: 212.69 MiB / 212.69 MiB [ 100.00% 14.08 MiB p/s 16s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.20.2 preload ...
    > preloaded-images-k8s-v8-v1....: 491.22 MiB / 491.22 MiB  100.00% 2.52 MiB
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
(base) helix@localhost website % which minikube
/usr/local/bin/minikube
(base) helix@localhost website % gcloud auth application-default set-quota-project
ERROR: (gcloud.auth.application-default.set-quota-project) argument QUOTA_PROJECT_ID: Must be specified.
Usage: gcloud auth application-default set-quota-project QUOTA_PROJECT_ID [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud auth application-default set-quota-project --help
(base) helix@localhost website % gcloud beta auth application-default set-quota-project
You do not currently have this command group installed.  Using it 
requires the installation of components: [beta]


Your current Cloud SDK version is: 326.0.0
Installing components from version: 326.0.0

┌─────────────────────────────────────────────┐
│     These components will be installed.     │
├──────────────────────┬────────────┬─────────┤
│         Name         │  Version   │   Size  │
├──────────────────────┼────────────┼─────────┤
│ gcloud Beta Commands │ 2019.05.17 │ < 1 MiB │
└──────────────────────┴────────────┴─────────┘

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Do you want to continue (Y/n)?  y

╔════════════════════════════════════════════════════════════╗
╠═ Creating update staging area                             ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: gcloud Beta Commands                         ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Creating backup and activating new installation          ═╣
╚════════════════════════════════════════════════════════════╝

Performing post processing steps...done.                                       

Update done!

Restarting command:
  $ gcloud beta auth application-default set-quota-project

ERROR: (gcloud.beta.auth.application-default.set-quota-project) argument QUOTA_PROJECT_ID: Must be specified.
Usage: gcloud beta auth application-default set-quota-project QUOTA_PROJECT_ID [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud beta auth application-default set-quota-project --help
(base) helix@localhost website % gcloud components update
Beginning update. This process may take several minutes.

All components are up to date.
(base) helix@localhost website % gcloud components install skaffold


Your current Cloud SDK version is: 326.0.0
Installing components from version: 326.0.0

┌───────────────────────────────────────────────────────────────────┐
│                These components will be installed.                │
├──────────────────────┬─────────────────────┬──────────────────────┤
│         Name         │       Version       │         Size         │
├──────────────────────┼─────────────────────┼──────────────────────┤
│ Skaffold             │              1.19.0 │             17.0 MiB │
│ kubectl              │             1.17.14 │              < 1 MiB │
│ kubectl              │             1.17.14 │             74.0 MiB │
└──────────────────────┴─────────────────────┴──────────────────────┘

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Do you want to continue (Y/n)?  y

╔════════════════════════════════════════════════════════════╗
╠═ Creating update staging area                             ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Skaffold                                     ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Skaffold                                     ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: kubectl                                      ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: kubectl                                      ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Creating backup and activating new installation          ═╣
╚════════════════════════════════════════════════════════════╝

Performing post processing steps...done.                                       

Update done!

WARNING:   There are other instances of Google Cloud Platform tools on your system PATH.
  Please remove the following to avoid confusion or accidental invocation:

  /Applications/Docker.app/Contents/Resources/bin/kubectl

  
(base) helix@localhost website % which kubectl
/usr/local/bin/kubectl
(base) helix@localhost website % rm /usr/local/bin/kubectl
(base) helix@localhost website % which kubectl            
/Users/helix/google-cloud-sdk/bin/kubectl
(base) helix@localhost website % brew install kustomize
Error: 
  homebrew-core is a shallow clone.
  homebrew-cask is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
These commands may take a few minutes to run due to the large size of the repositories.
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
==> Downloading https://homebrew.bintray.com/bottles/kustomize-3.9.2_2.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/b0c24578d829ae5ee53debb872488220c6410e39a605c4976b720d6ac105935a?response-content-disposition=attachment
######################################################################## 100.0%
==> Pouring kustomize-3.9.2_2.catalina.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/kustomize/3.9.2_2: 8 files, 44MB


Running `./run_test.sh -a` returns:

============================================================================= ERRORS ==============================================================================
__________________________________________________________ ERROR collecting webdriver_tests/base_test.py __________________________________________________________
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:57: in error_remapped_callable
    return callable_(*args, **kwargs)
../.env/lib/python3.8/site-packages/grpc/_channel.py:923: in __call__
    return _end_unary_response_blocking(state, call, False, None)
../.env/lib/python3.8/site-packages/grpc/_channel.py:826: in _end_unary_response_blocking
    raise _InactiveRpcError(state)
E   grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E   	status = StatusCode.PERMISSION_DENIED
E   	details = "Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist)."
E   	debug_error_string = "{"created":"@1612625301.883767000","description":"Error received from peer ipv6:[2607:f8b0:4000:802::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).","grpc_status":7}"
E   >

The above exception was the direct cause of the following exception:
webdriver_tests/base_test.py:18: in <module>
    from main import app
main.py:35: in <module>
    app = create_app()
__init__.py:119: in create_app
    secret_response = secret_client.access_secret_version(secret_name)
../.env/lib/python3.8/site-packages/google/cloud/secretmanager_v1/gapic/secret_manager_service_client.py:967: in access_secret_version
    return self._inner_api_calls["access_secret_version"](
../.env/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py:145: in __call__
    return wrapped_func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/retry.py:281: in retry_wrapped_func
    return retry_target(
../.env/lib/python3.8/site-packages/google/api_core/retry.py:184: in retry_target
    return target()
../.env/lib/python3.8/site-packages/google/api_core/timeout.py:214: in func_with_timeout
    return func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:59: in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
<string>:3: in raise_from
    ???
E   google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).
__________________________________________________________ ERROR collecting webdriver_tests/base_test.py __________________________________________________________
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:57: in error_remapped_callable
    return callable_(*args, **kwargs)
../.env/lib/python3.8/site-packages/grpc/_channel.py:923: in __call__
    return _end_unary_response_blocking(state, call, False, None)
../.env/lib/python3.8/site-packages/grpc/_channel.py:826: in _end_unary_response_blocking
    raise _InactiveRpcError(state)
E   grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E   	status = StatusCode.PERMISSION_DENIED
E   	details = "Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist)."
E   	debug_error_string = "{"created":"@1612625303.010014000","description":"Error received from peer ipv6:[2607:f8b0:4002:c10::5f]:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).","grpc_status":7}"
E   >

The above exception was the direct cause of the following exception:
webdriver_tests/base_test.py:18: in <module>
    from main import app
main.py:35: in <module>
    app = create_app()
__init__.py:119: in create_app
    secret_response = secret_client.access_secret_version(secret_name)
../.env/lib/python3.8/site-packages/google/cloud/secretmanager_v1/gapic/secret_manager_service_client.py:967: in access_secret_version
    return self._inner_api_calls["access_secret_version"](
../.env/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py:145: in __call__
    return wrapped_func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/retry.py:281: in retry_wrapped_func
    return retry_target(
../.env/lib/python3.8/site-packages/google/api_core/retry.py:184: in retry_target
    return target()
../.env/lib/python3.8/site-packages/google/api_core/timeout.py:214: in func_with_timeout
    return func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:59: in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
<string>:3: in raise_from
    ???
E   google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).
_____________________________________________________ ERROR collecting webdriver_tests/place_explorer_test.py _____________________________________________________
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:57: in error_remapped_callable
    return callable_(*args, **kwargs)
../.env/lib/python3.8/site-packages/grpc/_channel.py:923: in __call__
    return _end_unary_response_blocking(state, call, False, None)
../.env/lib/python3.8/site-packages/grpc/_channel.py:826: in _end_unary_response_blocking
    raise _InactiveRpcError(state)
E   grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E   	status = StatusCode.PERMISSION_DENIED
E   	details = "Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist)."
E   	debug_error_string = "{"created":"@1612625304.066578000","description":"Error received from peer ipv6:[2607:f8b0:4000:816::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).","grpc_status":7}"
E   >

The above exception was the direct cause of the following exception:
webdriver_tests/place_explorer_test.py:17: in <module>
    from webdriver_tests.base_test import WebdriverBaseTest
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
../.env/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
webdriver_tests/base_test.py:18: in <module>
    from main import app
main.py:35: in <module>
    app = create_app()
__init__.py:119: in create_app
    secret_response = secret_client.access_secret_version(secret_name)
../.env/lib/python3.8/site-packages/google/cloud/secretmanager_v1/gapic/secret_manager_service_client.py:967: in access_secret_version
    return self._inner_api_calls["access_secret_version"](
../.env/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py:145: in __call__
    return wrapped_func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/retry.py:281: in retry_wrapped_func
    return retry_target(
../.env/lib/python3.8/site-packages/google/api_core/retry.py:184: in retry_target
    return target()
../.env/lib/python3.8/site-packages/google/api_core/timeout.py:214: in func_with_timeout
    return func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:59: in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
<string>:3: in raise_from
    ???
E   google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).
________________________________________________________ ERROR collecting webdriver_tests/scatter_test.py _________________________________________________________
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:57: in error_remapped_callable
    return callable_(*args, **kwargs)
../.env/lib/python3.8/site-packages/grpc/_channel.py:923: in __call__
    return _end_unary_response_blocking(state, call, False, None)
../.env/lib/python3.8/site-packages/grpc/_channel.py:826: in _end_unary_response_blocking
    raise _InactiveRpcError(state)
E   grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E   	status = StatusCode.PERMISSION_DENIED
E   	details = "Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist)."
E   	debug_error_string = "{"created":"@1612625306.900509000","description":"Error received from peer ipv6:[2607:f8b0:4000:80e::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).","grpc_status":7}"
E   >

The above exception was the direct cause of the following exception:
webdriver_tests/scatter_test.py:16: in <module>
    from webdriver_tests.base_test import WebdriverBaseTest
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
../.env/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
webdriver_tests/base_test.py:18: in <module>
    from main import app
main.py:35: in <module>
    app = create_app()
__init__.py:119: in create_app
    secret_response = secret_client.access_secret_version(secret_name)
../.env/lib/python3.8/site-packages/google/cloud/secretmanager_v1/gapic/secret_manager_service_client.py:967: in access_secret_version
    return self._inner_api_calls["access_secret_version"](
../.env/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py:145: in __call__
    return wrapped_func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/retry.py:281: in retry_wrapped_func
    return retry_target(
../.env/lib/python3.8/site-packages/google/api_core/retry.py:184: in retry_target
    return target()
../.env/lib/python3.8/site-packages/google/api_core/timeout.py:214: in func_with_timeout
    return func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:59: in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
<string>:3: in raise_from
    ???
E   google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).
________________________________________________________ ERROR collecting webdriver_tests/timeline_test.py ________________________________________________________
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:57: in error_remapped_callable
    return callable_(*args, **kwargs)
../.env/lib/python3.8/site-packages/grpc/_channel.py:923: in __call__
    return _end_unary_response_blocking(state, call, False, None)
../.env/lib/python3.8/site-packages/grpc/_channel.py:826: in _end_unary_response_blocking
    raise _InactiveRpcError(state)
E   grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E   	status = StatusCode.PERMISSION_DENIED
E   	details = "Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist)."
E   	debug_error_string = "{"created":"@1612625307.966213000","description":"Error received from peer ipv6:[2607:f8b0:4000:80c::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).","grpc_status":7}"
E   >

The above exception was the direct cause of the following exception:
webdriver_tests/timeline_test.py:17: in <module>
    from webdriver_tests.base_test import WebdriverBaseTest
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
../.env/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
webdriver_tests/base_test.py:18: in <module>
    from main import app
main.py:35: in <module>
    app = create_app()
__init__.py:119: in create_app
    secret_response = secret_client.access_secret_version(secret_name)
../.env/lib/python3.8/site-packages/google/cloud/secretmanager_v1/gapic/secret_manager_service_client.py:967: in access_secret_version
    return self._inner_api_calls["access_secret_version"](
../.env/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py:145: in __call__
    return wrapped_func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/retry.py:281: in retry_wrapped_func
    return retry_target(
../.env/lib/python3.8/site-packages/google/api_core/retry.py:184: in retry_target
    return target()
../.env/lib/python3.8/site-packages/google/api_core/timeout.py:214: in func_with_timeout
    return func(*args, **kwargs)
../.env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:59: in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
<string>:3: in raise_from
    ???
E   google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/datcom-website-dev/secrets/maps-api-key/versions/1' (or it may not exist).
======================================================================== warnings summary =========================================================================
../.env/lib/python3.8/site-packages/google/auth/_default.py:69
../.env/lib/python3.8/site-packages/google/auth/_default.py:69
../.env/lib/python3.8/site-packages/google/auth/_default.py:69
../.env/lib/python3.8/site-packages/google/auth/_default.py:69
../.env/lib/python3.8/site-packages/google/auth/_default.py:69
  /Users/helix/Library/Data/website/.env/lib/python3.8/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
    warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
===================================================================== short test summary info =====================================================================
ERROR webdriver_tests/base_test.py - google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/d...
ERROR webdriver_tests/base_test.py - google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/d...
ERROR webdriver_tests/place_explorer_test.py - google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource '...
ERROR webdriver_tests/scatter_test.py - google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'project...
ERROR webdriver_tests/timeline_test.py - google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projec...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======== 5 warnings, 5 errors in 8.30s ===========

**Comment by shifucun** [comment]
You might need to set a default gcp project locally by running "gcloud config set project <PROJECT_ID>" and you should have reasonable permission on  the project <PROEJCT_ID>.

The "minikube" flow requires our data storage permission and meant for our internal developer. If you want to test out the website frontend, then using the "lite" flow should be good enough.
